[project]
name = "streamlit-private-prototyping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.3",
    "sentence-transformers>=3.4.1",
    "streamlit>=1.43.0",
]
